"""

Generated by noogh-teacher
"""
from typing import Dict, Tuple

def neuron_short_filter(setup):
    if setup.get('volume', 0) < 2500000: return False, 0, 'Low volume'
    return True, 0.8, 'Good'
