"""

Generated by noogh-teacher
"""
from typing import Dict, Tuple

def neuron_long_filter(setup):
    if setup.get('taker_buy_ratio', 0) > 0.58: return False, 0, 'Too high'
    return True, 0.8, 'Good'
