#!/usr/bin/env python3
"""
NOOGH Distillation Training — Teacher → Student Knowledge Transfer
==================================================================
Trains the 7B Student model on knowledge distilled from the 32B Teacher.

Data source: data/distillation/training_ready.jsonl
    - Automatically generated by the evolution pipeline
    - Contains Brain refactoring examples, agent designs, innovations
    - Already in ChatML format (messages: [system, user, assistant])

This can run:
    1. Manually:  python3 train_distilled.py
    2. Scheduled: via the evolution daemon (auto-distillation)

Uses incremental LoRA training — each run fine-tunes the existing adapter
rather than retraining from scratch.
"""

import os
import json
import time
import torch
import logging
from pathlib import Path
from typing import Dict, Any, Optional

logger = logging.getLogger("distillation_trainer")

# ============================================================================
# CONFIG
# ============================================================================

# Data paths
DISTILLATION_DATA = Path(__file__).parent / "data/distillation/training_ready.jsonl"
TRAJECTORIES_FILE = Path(__file__).parent / "data/distillation/teacher_trajectories.jsonl"

# Model config
BASE_MODEL = "unsloth/Qwen2.5-7B-Instruct-bnb-4bit"
EXISTING_LORA = Path(__file__).parent / "noogh_qwen7b_lora"
OUTPUT_DIR = Path(__file__).parent / "models/noogh_distilled_7b"

# Training (conservative — runs alongside services)
MAX_SEQ_LENGTH = 1024
BATCH_SIZE = 1
GRADIENT_ACCUMULATION = 8
LEARNING_RATE = 5e-5   # Lower LR for incremental training
EPOCHS = 1             # Single pass for continuous learning

# Tracking
TRAINING_LOG = Path(__file__).parent / "data/distillation/training_log.jsonl"

# ============================================================================
# HELPER: ChatML Formatter
# ============================================================================

def format_chatml(messages: list) -> str:
    """Convert messages array to ChatML text format for Qwen."""
    parts = []
    for msg in messages:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        parts.append(f"<|im_start|>{role}\n{content}\n<|im_end|>")
    return "\n".join(parts)

# ============================================================================
# LOAD DISTILLATION DATA
# ============================================================================

def load_distillation_data(min_quality: float = 0.6) -> list:
    """
    Load training data from distillation pipeline.
    
    Returns list of formatted training examples.
    """
    if not DISTILLATION_DATA.exists():
        logger.error(f"No distillation data at {DISTILLATION_DATA}")
        return []
    
    examples = []
    stats = {"total": 0, "loaded": 0, "skipped_short": 0, "categories": {}}
    
    with open(DISTILLATION_DATA, 'r', encoding='utf-8') as f:
        for line in f:
            stats["total"] += 1
            try:
                item = json.loads(line.strip())
                messages = item.get("messages", [])
                
                if not messages or len(messages) < 2:
                    continue
                
                # Format to ChatML text
                text = format_chatml(messages)
                
                # Skip very short examples (likely errors)
                if len(text) < 100:
                    stats["skipped_short"] += 1
                    continue
                
                # Truncate very long examples
                if len(text) > MAX_SEQ_LENGTH * 4:
                    text = text[:MAX_SEQ_LENGTH * 4]
                
                examples.append({"text": text})
                stats["loaded"] += 1
                
                # Track category (from original trajectory data, if available)
                cat = item.get("category", "unknown")
                stats["categories"][cat] = stats["categories"].get(cat, 0) + 1
                
            except json.JSONDecodeError:
                continue
    
    logger.info(
        f"📚 Loaded {stats['loaded']}/{stats['total']} distillation examples "
        f"(skipped {stats['skipped_short']} short)"
    )
    
    return examples


# ============================================================================
# TRAINING
# ============================================================================

def train(dry_run: bool = False) -> Dict[str, Any]:
    """
    Run distillation training.
    
    Args:
        dry_run: If True, only load data and report stats without training
    
    Returns:
        Training result dict
    """
    start_time = time.time()
    
    print("\n" + "=" * 60)
    print("🧠→📖 NOOGH Distillation Training — Teacher → Student")
    print("=" * 60 + "\n")
    
    # 1. Load distillation data
    examples = load_distillation_data()
    
    if not examples:
        return {"success": False, "error": "No training data available"}
    
    print(f"📊 Training examples: {len(examples)}")
    
    if dry_run:
        return {
            "success": True, 
            "dry_run": True,
            "examples": len(examples),
            "message": "Dry run — data loaded successfully"
        }
    
    # 2. GPU check
    if not torch.cuda.is_available():
        return {"success": False, "error": "No GPU available"}
    
    gpu_name = torch.cuda.get_device_name(0)
    gpu_mem = torch.cuda.get_device_properties(0).total_mem / 1e9
    print(f"🎮 GPU: {gpu_name} ({gpu_mem:.1f} GB)")
    
    # Check VRAM availability (need ~8GB free for 7B 4-bit)
    free_mem = (torch.cuda.get_device_properties(0).total_mem - torch.cuda.memory_allocated(0)) / 1e9
    if free_mem < 6:
        print(f"⚠️ Only {free_mem:.1f} GB free VRAM — may need to stop other services")
    
    # 3. Load model
    from unsloth import FastLanguageModel
    from trl import SFTTrainer
    from transformers import TrainingArguments
    from datasets import Dataset
    
    print(f"\n📦 Loading base model: {BASE_MODEL}")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=BASE_MODEL,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,
        load_in_4bit=True,
    )
    
    # 4. Apply LoRA (or load existing)
    if EXISTING_LORA.exists() and (EXISTING_LORA / "adapter_config.json").exists():
        print(f"🔗 Loading existing LoRA from {EXISTING_LORA}")
        from peft import PeftModel
        model = PeftModel.from_pretrained(model, str(EXISTING_LORA))
        # Make trainable again
        for param in model.parameters():
            if param.requires_grad:
                param.data = param.data.float()
    else:
        print("🔧 Creating new LoRA adapter...")
        model = FastLanguageModel.get_peft_model(
            model,
            r=32,
            target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                            "gate_proj", "up_proj", "down_proj"],
            lora_alpha=32,
            lora_dropout=0.05,
            bias="none",
            use_gradient_checkpointing="unsloth",
            random_state=42,
        )
    
    # 5. Prepare dataset
    dataset = Dataset.from_list(examples)
    split = dataset.train_test_split(test_size=min(0.1, 10/len(examples)), seed=42)
    train_dataset = split['train']
    eval_dataset = split['test']
    
    print(f"📈 Train: {len(train_dataset)}, Eval: {len(eval_dataset)}")
    
    # 6. Training args (conservative for background training)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    training_args = TrainingArguments(
        output_dir=str(OUTPUT_DIR),
        per_device_train_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRADIENT_ACCUMULATION,
        warmup_steps=10,
        num_train_epochs=EPOCHS,
        learning_rate=LEARNING_RATE,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=5,
        save_strategy="epoch",
        eval_strategy="epoch",
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="cosine",
        seed=42,
        report_to="none",
        gradient_checkpointing=True,
        # Conservative memory usage
        dataloader_num_workers=0,
        max_grad_norm=0.3,
    )
    
    # 7. Train
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        dataset_text_field="text",
        max_seq_length=MAX_SEQ_LENGTH,
        args=training_args,
    )
    
    print("\n" + "=" * 60)
    print("🏃 Starting Distillation Training...")
    print("=" * 60)
    
    train_result = trainer.train()
    
    # 8. Save
    print(f"\n💾 Saving distilled model to {OUTPUT_DIR}")
    model.save_pretrained(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    
    # 9. Log training run
    training_time = time.time() - start_time
    metrics = {
        k: float(v) if isinstance(v, (int, float)) else str(v) 
        for k, v in (train_result.metrics or {}).items()
    }
    
    log_entry = {
        "timestamp": time.time(),
        "examples": len(examples),
        "training_time_seconds": round(training_time, 1),
        "epochs": EPOCHS,
        "learning_rate": LEARNING_RATE,
        "metrics": metrics,
        "output_dir": str(OUTPUT_DIR),
    }
    
    TRAINING_LOG.parent.mkdir(parents=True, exist_ok=True)
    with open(TRAINING_LOG, 'a', encoding='utf-8') as f:
        f.write(json.dumps(log_entry, ensure_ascii=False) + "\n")
    
    print("\n" + "=" * 60)
    print("✅ Distillation Training Complete!")
    print(f"   Examples: {len(examples)}")
    print(f"   Time: {training_time:.0f}s")
    print(f"   Model: {OUTPUT_DIR}")
    print(f"   Loss: {metrics.get('train_loss', '?')}")
    print("=" * 60 + "\n")
    
    return {
        "success": True,
        "examples": len(examples),
        "training_time": training_time,
        "metrics": metrics,
        "output_dir": str(OUTPUT_DIR),
    }


# ============================================================================
# AUTO-DISTILLATION: Called by Evolution Controller
# ============================================================================

async def auto_distill(min_new_trajectories: int = 50) -> Dict[str, Any]:
    """
    Called automatically by the evolution pipeline.
    
    Only trains if enough new trajectories have accumulated since last training.
    
    Args:
        min_new_trajectories: Minimum new examples needed to trigger training
    
    Returns:
        Result dict
    """
    # Check how many trajectories we have vs last training
    if not TRAJECTORIES_FILE.exists():
        return {"skipped": True, "reason": "No trajectories file"}
    
    total_trajectories = sum(1 for _ in open(TRAJECTORIES_FILE, 'r'))
    
    # Check last training count
    last_trained_count = 0
    if TRAINING_LOG.exists():
        try:
            lines = open(TRAINING_LOG, 'r').readlines()
            if lines:
                last = json.loads(lines[-1])
                last_trained_count = last.get("examples", 0)
        except Exception:
            pass
    
    new_count = total_trajectories - last_trained_count
    
    if new_count < min_new_trajectories:
        return {
            "skipped": True,
            "reason": f"Only {new_count} new trajectories (need {min_new_trajectories})",
            "total": total_trajectories,
            "last_trained": last_trained_count,
        }
    
    logger.info(
        f"📚 Auto-distillation: {new_count} new trajectories "
        f"(total={total_trajectories}) — starting training"
    )
    
    # First export latest trajectories
    try:
        from unified_core.evolution.distillation_collector import get_distillation_collector
        collector = get_distillation_collector()
        collector.export_training_data(min_quality=0.6)
    except Exception as e:
        logger.warning(f"Pre-training export failed: {e}")
    
    # Run training in executor to avoid blocking event loop
    import asyncio
    loop = asyncio.get_event_loop()
    result = await loop.run_in_executor(None, lambda: train(dry_run=False))
    
    return result


# ============================================================================
# CLI
# ============================================================================

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="NOOGH Distillation Training")
    parser.add_argument("--dry-run", action="store_true", help="Only load data, don't train")
    parser.add_argument("--min-quality", type=float, default=0.6, help="Minimum quality score filter")
    args = parser.parse_args()
    
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    if args.dry_run:
        result = train(dry_run=True)
    else:
        result = train()
    
    print(f"\nResult: {json.dumps(result, indent=2, ensure_ascii=False)}")
