"""
Agent Factory — Autonomous Agent Generation System v1.0
=======================================================

Enables the evolution pipeline to create NEW agents autonomously.

Architecture:
  1. AgentFactory analyzes system gaps (missing capabilities)
  2. Uses the Brain (Teacher LLM) to design an agent spec
  3. Generates agent code from the spec
  4. Validates: syntax, contract compliance, safety
  5. Deploys to agents/ directory
  6. Registers with AgentRole and MessageBus

Safety Layers:
  - Generated code is sandboxed and validated via AST
  - No network, file-write, or system-exec capabilities by default
  - Policy Gate reviews before deployment
  - All agents must inherit from AgentWorker
"""

import ast
import hashlib
import json
import logging
import os
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger("unified_core.evolution.agent_factory")

# ============================================================
#  Agent Blueprint — Design spec before code generation
# ============================================================

@dataclass
class AgentBlueprint:
    """Blueprint for a new agent before code generation."""
    agent_id: str
    name: str              # e.g. "HealthMonitorAgent"
    role: str              # e.g. "health_monitor"
    description: str       # What does this agent do?
    capabilities: List[str]  # What capabilities it handles
    handlers: List[Dict[str, str]]  # [{name, description, capability}]
    risk_level: str = "SAFE"  # SAFE | RESTRICTED | DANGEROUS
    
    # Metadata
    reason: str = ""       # Why was this agent needed?
    created_at: float = field(default_factory=time.time)
    generated_code: str = ""
    validation_result: Optional[Dict] = None


# ============================================================
#  Agent Templates — For deterministic generation
# ============================================================

AGENT_TEMPLATE = '''"""
NOOGH {class_name}

Auto-generated agent by AgentFactory v1.0
Purpose: {description}
Generated: {timestamp}
Reason: {reason}
"""

import asyncio
import logging
from typing import Dict, Any

from unified_core.orchestration.agent_worker import AgentWorker
from unified_core.orchestration.messages import AgentRole

logger = logging.getLogger("agents.{module_name}")


class {class_name}(AgentWorker):
    """
    {description}
    
    Capabilities:
{capabilities_doc}
    
    Auto-generated by NOOGH AgentFactory.
    """
    
    def __init__(self):
        custom_handlers = {{
{handler_registrations}
        }}
        
        # Use dynamic role registration
        role = AgentRole("{role}")
        super().__init__(role, custom_handlers)
        logger.info("✅ {class_name} initialized")
    
{handler_methods}


# ============================================================
# Entry Point
# ============================================================

async def main():
    """Start the {class_name}."""
    logger.info("🚀 Starting {class_name}...")
    agent = {class_name}()
    agent.start()
    
    try:
        while True:
            await asyncio.sleep(1)
    except KeyboardInterrupt:
        logger.info("🛑 {class_name} stopping...")


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    asyncio.run(main())
'''

HANDLER_TEMPLATE = '''    async def {method_name}(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """
        {description}
        
        Capability: {capability}
        """
        try:
            arguments = task.get("arguments", {{}})
            
{handler_body}
            
        except Exception as e:
            logger.error(f"{method_name} failed: {{e}}")
            return {{"success": False, "error": str(e)}}
'''


# ============================================================
#  Agent Factory — The Builder
# ============================================================

class AgentFactory:
    """
    Builds new agents for the NOOGH system.
    
    Two modes:
    1. Template mode (deterministic) — uses predefined templates
    2. Brain mode (LLM-assisted) — asks the Brain to design handlers
    """
    
    # Registry of built-in blueprints for common needs
    BUILTIN_BLUEPRINTS = {
        "health_monitor": AgentBlueprint(
            agent_id="health_monitor",
            name="HealthMonitorAgent",
            role="health_monitor",
            description="Monitors system health metrics and raises alerts",
            capabilities=["MONITOR_HEALTH", "CHECK_SERVICES", "REPORT_ANOMALIES"],
            handlers=[
                {
                    "name": "_monitor_health",
                    "description": "Check CPU, RAM, disk, and service status",
                    "capability": "MONITOR_HEALTH",
                    "body": (
                        '            import psutil\n'
                        '            cpu = psutil.cpu_percent(interval=0.5)\n'
                        '            ram = psutil.virtual_memory().percent\n'
                        '            disk = psutil.disk_usage("/").percent\n'
                        '            \n'
                        '            alerts = []\n'
                        '            if cpu > 90: alerts.append(f"CPU critical: {cpu}%")\n'
                        '            if ram > 85: alerts.append(f"RAM high: {ram}%")\n'
                        '            if disk > 90: alerts.append(f"Disk almost full: {disk}%")\n'
                        '            \n'
                        '            return {\n'
                        '                "success": True,\n'
                        '                "metrics": {"cpu": cpu, "ram": ram, "disk": disk},\n'
                        '                "alerts": alerts,\n'
                        '                "status": "critical" if alerts else "healthy"\n'
                        '            }'
                    )
                },
                {
                    "name": "_check_services",
                    "description": "Verify critical services are running",
                    "capability": "CHECK_SERVICES",
                    "body": (
                        '            import subprocess\n'
                        '            services = ["noogh-agent", "redis-server"]\n'
                        '            results = {}\n'
                        '            for svc in services:\n'
                        '                try:\n'
                        '                    out = subprocess.run(\n'
                        '                        ["systemctl", "is-active", svc],\n'
                        '                        capture_output=True, text=True, timeout=5\n'
                        '                    )\n'
                        '                    results[svc] = out.stdout.strip()\n'
                        '                except Exception:\n'
                        '                    results[svc] = "unknown"\n'
                        '            \n'
                        '            return {"success": True, "services": results}'
                    )
                },
                {
                    "name": "_report_anomalies",
                    "description": "Analyze recent metrics for anomalies",
                    "capability": "REPORT_ANOMALIES",
                    "body": (
                        '            # Simple anomaly detection\n'
                        '            recent = arguments.get("recent_metrics", [])\n'
                        '            if not recent:\n'
                        '                return {"success": True, "anomalies": [], "message": "No data"}\n'
                        '            \n'
                        '            anomalies = []\n'
                        '            for m in recent:\n'
                        '                if m.get("cpu", 0) > 80:\n'
                        '                    anomalies.append({"type": "cpu_spike", "value": m["cpu"]})\n'
                        '                if m.get("ram", 0) > 80:\n'
                        '                    anomalies.append({"type": "ram_spike", "value": m["ram"]})\n'
                        '            \n'
                        '            return {"success": True, "anomalies": anomalies}'
                    )
                }
            ],
            reason="System needs autonomous health monitoring",
            risk_level="RESTRICTED"
        ),
        
        "log_analyzer": AgentBlueprint(
            agent_id="log_analyzer",
            name="LogAnalyzerAgent",
            role="log_analyzer",
            description="Analyzes system logs for errors and patterns",
            capabilities=["ANALYZE_LOGS", "DETECT_ERROR_PATTERNS", "SUMMARIZE_LOGS"],
            handlers=[
                {
                    "name": "_analyze_logs",
                    "description": "Parse and analyze recent log entries",
                    "capability": "ANALYZE_LOGS",
                    "body": (
                        '            log_path = arguments.get("log_path", "/var/log/syslog")\n'
                        '            lines = arguments.get("lines", 100)\n'
                        '            \n'
                        '            try:\n'
                        '                import subprocess\n'
                        '                result = subprocess.run(\n'
                        '                    ["tail", "-n", str(lines), log_path],\n'
                        '                    capture_output=True, text=True, timeout=10\n'
                        '                )\n'
                        '                log_content = result.stdout\n'
                        '            except Exception as e:\n'
                        '                return {"success": False, "error": f"Cannot read logs: {e}"}\n'
                        '            \n'
                        '            error_count = log_content.lower().count("error")\n'
                        '            warning_count = log_content.lower().count("warning")\n'
                        '            \n'
                        '            return {\n'
                        '                "success": True,\n'
                        '                "total_lines": len(log_content.splitlines()),\n'
                        '                "errors": error_count,\n'
                        '                "warnings": warning_count,\n'
                        '                "health": "good" if error_count < 5 else "degraded"\n'
                        '            }'
                    )
                },
                {
                    "name": "_detect_error_patterns",
                    "description": "Find recurring error patterns in logs",
                    "capability": "DETECT_ERROR_PATTERNS",
                    "body": (
                        '            from collections import Counter\n'
                        '            log_lines = arguments.get("log_lines", [])\n'
                        '            \n'
                        '            errors = [l for l in log_lines if "error" in l.lower()]\n'
                        '            # Extract error types\n'
                        '            patterns = Counter()\n'
                        '            for err in errors:\n'
                        '                # Simple: first 50 chars as pattern key\n'
                        '                key = err.strip()[:50]\n'
                        '                patterns[key] += 1\n'
                        '            \n'
                        '            recurring = [\n'
                        '                {"pattern": p, "count": c}\n'
                        '                for p, c in patterns.most_common(10)\n'
                        '                if c > 1\n'
                        '            ]\n'
                        '            \n'
                        '            return {"success": True, "recurring_errors": recurring}'
                    )
                },
                {
                    "name": "_summarize_logs",
                    "description": "Create a summary of log activity",
                    "capability": "SUMMARIZE_LOGS",
                    "body": (
                        '            log_lines = arguments.get("log_lines", [])\n'
                        '            \n'
                        '            summary = {\n'
                        '                "total": len(log_lines),\n'
                        '                "errors": sum(1 for l in log_lines if "error" in l.lower()),\n'
                        '                "warnings": sum(1 for l in log_lines if "warning" in l.lower()),\n'
                        '                "info": sum(1 for l in log_lines if "info" in l.lower()),\n'
                        '            }\n'
                        '            summary["health_score"] = max(0, 100 - summary["errors"] * 5 - summary["warnings"])\n'
                        '            \n'
                        '            return {"success": True, "summary": summary}'
                    )
                }
            ],
            reason="System needs log analysis capability",
            risk_level="RESTRICTED"
        ),
        
        # v5.1: Performance profiler — uses cProfile.runctx (NOT exec) with restricted globals
        "performance_profiler": AgentBlueprint(
            agent_id="performance_profiler",
            name="PerformanceProfilerAgent",
            role="performance_profiler",
            description="Profile Python code performance and identify slow functions",
            capabilities=["PROFILE_CODE", "IDENTIFY_BOTTLENECKS"],
            handlers=[
                {
                    "name": "_profile_code",
                    "description": "Profile Python code safely using cProfile with restricted globals",
                    "capability": "PROFILE_CODE",
                    "body": (
                        '            code = task.get("arguments", {}).get("code")\n'
                        '            if not code:\n'
                        '                return {"success": False, "error": "No code provided"}\n'
                        '            \n'
                        '            safe_builtins = {\n'
                        '                "print": print, "len": len, "range": range,\n'
                        '                "int": int, "float": float, "str": str,\n'
                        '                "list": list, "dict": dict, "tuple": tuple,\n'
                        '                "set": set, "enumerate": enumerate, "zip": zip,\n'
                        '                "any": any, "all": all, "sum": sum,\n'
                        '                "min": min, "max": max, "abs": abs,\n'
                        '                "round": round, "pow": pow, "divmod": divmod,\n'
                        '                "isinstance": isinstance, "type": type,\n'
                        '                "sorted": sorted, "reversed": reversed,\n'
                        '                "open": None, "eval": None, "exec": None,\n'
                        '                "__import__": None, "compile": None,\n'
                        '            }\n'
                        '            safe_globals = {"__builtins__": safe_builtins}\n'
                        '            \n'
                        '            import cProfile, io, pstats\n'
                        '            pr = cProfile.Profile()\n'
                        '            pr.runctx(code, safe_globals, {})\n'
                        '            \n'
                        '            s = io.StringIO()\n'
                        '            ps = pstats.Stats(pr, stream=s).sort_stats("cumulative")\n'
                        '            ps.print_stats()\n'
                        '            return {"success": True, "performance_metrics": s.getvalue()}'
                    )
                },
                {
                    "name": "_identify_bottlenecks",
                    "description": "Parse cProfile output to find the slowest functions",
                    "capability": "IDENTIFY_BOTTLENECKS",
                    "body": (
                        '            metrics = task.get("arguments", {}).get("performance_metrics", "")\n'
                        '            if not metrics:\n'
                        '                return {"success": False, "error": "No performance metrics"}\n'
                        '            \n'
                        '            lines = metrics.split("\\n")\n'
                        '            bottlenecks = []\n'
                        '            in_stats = False\n'
                        '            for line in lines:\n'
                        '                if "ncalls" in line and "tottime" in line:\n'
                        '                    in_stats = True\n'
                        '                    continue\n'
                        '                if in_stats and line.strip():\n'
                        '                    parts = line.split()\n'
                        '                    if len(parts) >= 6:\n'
                        '                        try:\n'
                        '                            bottlenecks.append({\n'
                        '                                "function": parts[5],\n'
                        '                                "cumtime": float(parts[3]),\n'
                        '                                "calls": parts[0],\n'
                        '                            })\n'
                        '                        except (ValueError, IndexError):\n'
                        '                            pass\n'
                        '            \n'
                        '            bottlenecks.sort(key=lambda x: x["cumtime"], reverse=True)\n'
                        '            return {"success": True, "bottlenecks": bottlenecks[:10]}'
                    )
                }
            ],
            reason="Code refactoring needs performance data to prioritize",
            risk_level="RESTRICTED"
        ),
        
        # v10: Backup agent — built-in to avoid vLLM dependency
        "backup_agent": AgentBlueprint(
            agent_id="backup_agent",
            name="BackupAgentAgent",
            role="backup_agent",
            description="Manage system backups and ensure data recovery capability",
            capabilities=["CREATE_BACKUP", "VERIFY_BACKUP"],
            handlers=[
                {
                    "name": "_create_backup",
                    "description": "Creates a backup of specified directories",
                    "capability": "CREATE_BACKUP",
                    "body": (
                        '            src = task.get("arguments", {}).get("source_dir")\n'
                        '            dst = task.get("arguments", {}).get("dest_dir")\n'
                        '            if not src or not dst:\n'
                        '                return {"success": False, "error": "Missing source/destination"}\n'
                        '            import os, shutil\n'
                        '            try:\n'
                        '                shutil.copytree(src, dst, dirs_exist_ok=True)\n'
                        '                file_count = sum(len(f) for _, _, f in os.walk(dst))\n'
                        '                return {"success": True, "message": f"Backup created: {file_count} files"}\n'
                        '            except Exception as e:\n'
                        '                return {"success": False, "error": str(e)}'
                    )
                },
                {
                    "name": "_verify_backup",
                    "description": "Verifies backup integrity by comparing file counts",
                    "capability": "VERIFY_BACKUP",
                    "body": (
                        '            src = task.get("arguments", {}).get("source_dir")\n'
                        '            dst = task.get("arguments", {}).get("dest_dir")\n'
                        '            if not src or not dst:\n'
                        '                return {"success": False, "error": "Missing source/destination"}\n'
                        '            import os\n'
                        '            try:\n'
                        '                src_count = sum(len(f) for _, _, f in os.walk(src))\n'
                        '                dst_count = sum(len(f) for _, _, f in os.walk(dst))\n'
                        '                match = src_count == dst_count\n'
                        '                return {"success": True, "verified": match, "src_files": src_count, "dst_files": dst_count}\n'
                        '            except Exception as e:\n'
                        '                return {"success": False, "error": str(e)}'
                    )
                }
            ],
            reason="System resilience requires automated backups",
            risk_level="RESTRICTED"
        ),
    }
    
    def __init__(self):
        self.agents_dir = Path(__file__).parent.parent.parent / "agents"
        self.agents_dir.mkdir(exist_ok=True)
        self._generated_agents = []
        self._registry_path = self.agents_dir / "agent_registry.json"
        self._load_registry()
        logger.info(f"🏭 AgentFactory initialized — agents dir: {self.agents_dir}")
    
    def _load_registry(self):
        """Load the registry of generated agents."""
        if self._registry_path.exists():
            try:
                with open(self._registry_path, 'r') as f:
                    self._generated_agents = json.load(f)
            except Exception:
                self._generated_agents = []
        else:
            self._generated_agents = []
    
    def _save_registry(self):
        """Save the registry of generated agents (deduplicates by role)."""
        # Defense-in-depth: deduplicate by role, keeping the latest entry
        seen_roles = {}
        for agent in self._generated_agents:
            role = agent.get("role", "unknown")
            seen_roles[role] = agent  # Last one wins (most recent)
        self._generated_agents = list(seen_roles.values())
        
        with open(self._registry_path, 'w') as f:
            json.dump(self._generated_agents, f, indent=2, default=str)
    
    # ─── Main API ──────────────────────────────────────────
    
    def generate_agent(self, blueprint_id: str = None, 
                        blueprint: AgentBlueprint = None) -> Dict[str, Any]:
        """
        Generate a new agent from a blueprint.
        
        Args:
            blueprint_id: ID of a builtin blueprint (e.g. "health_monitor")
            blueprint: Custom AgentBlueprint object
            
        Returns:
            {"success": bool, "agent_file": str, "class_name": str, ...}
        """
        # Get blueprint
        if blueprint is None:
            if blueprint_id not in self.BUILTIN_BLUEPRINTS:
                return {"success": False, "error": f"Unknown blueprint: {blueprint_id}"}
            blueprint = self.BUILTIN_BLUEPRINTS[blueprint_id]
        
        # Check if already generated
        agent_file = self.agents_dir / f"{blueprint.role}_agent.py"
        if agent_file.exists():
            return {
                "success": False, 
                "error": f"Agent already exists: {agent_file}",
                "hint": "Delete the file first or use a different role"
            }
        
        # Step 1: Generate code from blueprint
        code = self._generate_code(blueprint)
        
        # Step 2: Validate the generated code
        validation = self._validate_agent_code(code, blueprint)
        if not validation["valid"]:
            return {
                "success": False, 
                "error": "Validation failed",
                "violations": validation["violations"]
            }
        
        # Step 3: Write the agent file
        with open(agent_file, 'w', encoding='utf-8') as f:
            f.write(code)
        
        # Step 4: Register in the AgentRole enum (dynamic)
        self._register_role(blueprint.role)
        
        # Step 5: Update registry
        entry = {
            "agent_id": blueprint.agent_id,
            "name": blueprint.name,
            "role": blueprint.role,
            "file": str(agent_file),
            "capabilities": blueprint.capabilities,
            "reason": blueprint.reason,
            "created_at": time.time(),
            "validation": validation
        }
        self._generated_agents.append(entry)
        self._save_registry()
        
        logger.warning(
            f"🏭 NEW AGENT GENERATED: {blueprint.name} "
            f"({len(blueprint.capabilities)} capabilities) → {agent_file.name}"
        )
        
        return {
            "success": True,
            "agent_file": str(agent_file),
            "class_name": blueprint.name,
            "role": blueprint.role,
            "capabilities": blueprint.capabilities,
            "validation": validation
        }
    
    # ─── Code Generation ──────────────────────────────────
    
    def _generate_code(self, bp: AgentBlueprint) -> str:
        """Generate Python code for an agent from blueprint."""
        
        # Build capabilities doc
        capabilities_doc = "\n".join(
            f"    - {cap}" for cap in bp.capabilities
        )
        
        # Build handler registrations
        registrations = []
        for h in bp.handlers:
            registrations.append(
                f'            "{h["capability"]}": self.{h["name"]},'
            )
        handler_registrations = "\n".join(registrations)
        
        # Build handler methods
        methods = []
        for h in bp.handlers:
            body = h.get("body", '            return {"success": True, "message": "Not implemented"}')
            method = HANDLER_TEMPLATE.format(
                method_name=h["name"],
                description=h["description"],
                capability=h["capability"],
                handler_body=body
            )
            methods.append(method)
        handler_methods = "\n".join(methods)
        
        # Build module name
        module_name = bp.role.lower().replace(" ", "_")
        
        code = AGENT_TEMPLATE.format(
            class_name=bp.name,
            description=bp.description,
            timestamp=time.strftime("%Y-%m-%d %H:%M:%S"),
            reason=bp.reason,
            module_name=module_name,
            capabilities_doc=capabilities_doc,
            handler_registrations=handler_registrations,
            role=bp.role,
            handler_methods=handler_methods
        )
        
        return code
    
    # ─── Validation ────────────────────────────────────────
    
    def _validate_agent_code(self, code: str, bp: AgentBlueprint) -> Dict[str, Any]:
        """
        Validate generated agent code for safety and contract compliance.
        
        Checks:
        1. Syntax (AST parse)
        2. Contract compliance (inherits AgentWorker, has __init__)
        3. Safety (no dangerous imports, no eval, no exec)
        4. No network calls, no file writes without approval
        """
        violations = []
        
        # 1. Syntax check
        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            return {"valid": False, "violations": [f"Syntax error: {e}"]}
        
        # 2. Contract compliance: must have a class inheriting AgentWorker
        classes = [n for n in ast.walk(tree) if isinstance(n, ast.ClassDef)]
        agent_class = None
        for cls in classes:
            for base in cls.bases:
                if isinstance(base, ast.Name) and base.id == "AgentWorker":
                    agent_class = cls
                    break
                elif isinstance(base, ast.Attribute) and base.attr == "AgentWorker":
                    agent_class = cls
                    break
        
        if agent_class is None:
            violations.append("No class inheriting AgentWorker found")
        else:
            # Must have __init__
            has_init = any(
                isinstance(n, ast.FunctionDef) and n.name == "__init__"
                for n in ast.walk(agent_class)
            )
            if not has_init:
                violations.append("Agent class missing __init__")
            
            # Must call super().__init__
            has_super = "super().__init__" in code
            if not has_super:
                violations.append("Agent __init__ must call super().__init__()")
        
        # 3. Safety: banned patterns
        banned_imports = {"subprocess", "shutil", "ctypes", "socket"}
        # Allow subprocess only for RESTRICTED+ agents
        if bp.risk_level == "SAFE":
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        if alias.name.split(".")[0] in banned_imports:
                            violations.append(f"Banned import for SAFE agent: {alias.name}")
                elif isinstance(node, ast.ImportFrom):
                    if node.module and node.module.split(".")[0] in banned_imports:
                        violations.append(f"Banned import for SAFE agent: {node.module}")
        
        # No eval/exec
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name):
                    if node.func.id in ("eval", "exec", "__import__"):
                        violations.append(f"Dangerous function call: {node.func.id}()")
        
        # 4. Size limits
        line_count = len(code.splitlines())
        if line_count > 500:
            violations.append(f"Agent too large: {line_count} lines (max 500)")
        
        return {
            "valid": len(violations) == 0,
            "violations": violations,
            "line_count": line_count,
            "class_name": agent_class.name if agent_class else None,
            "handler_count": len(bp.handlers)
        }
    
    # ─── Role Registration ─────────────────────────────────
    
    def _register_role(self, role: str):
        """
        Dynamically register a new AgentRole.
        
        Python Enums don't support dynamic members easily,
        so we check if the role already exists before adding.
        """
        from unified_core.orchestration.messages import AgentRole
        
        # Check if role already exists
        try:
            AgentRole(role)
            logger.info(f"AgentRole '{role}' already registered")
        except ValueError:
            # Not in enum — we'll need to handle this differently
            # For now, log a warning. The agent can use string matching.
            logger.warning(
                f"AgentRole '{role}' not in Enum — "
                f"agent will use string-based role matching"
            )
    
    # ─── Listing ───────────────────────────────────────────
    
    def list_agents(self) -> List[Dict[str, Any]]:
        """List all generated agents."""
        return self._generated_agents
    
    def list_available_blueprints(self) -> List[str]:
        """List available builtin blueprints."""
        return list(self.BUILTIN_BLUEPRINTS.keys())
    
    def get_stats(self) -> Dict[str, Any]:
        """Factory statistics."""
        return {
            "total_generated": len(self._generated_agents),
            "available_blueprints": list(self.BUILTIN_BLUEPRINTS.keys()),
            "agents_dir": str(self.agents_dir),
        }
    
    # ─── Brain-Designed Blueprints (LLM Mode) ──────────────
    
    def _get_brain_client(self):
        """Get a NeuralEngineClient pointing at the Teacher model."""
        if not hasattr(self, '_neural_client') or self._neural_client is None:
            from ..neural_bridge import NeuralEngineClient
            teacher_url = os.getenv("NOOGH_TEACHER_URL", os.getenv("NEURAL_ENGINE_URL"))
            teacher_mode = os.getenv("NOOGH_TEACHER_MODE", os.getenv("NEURAL_ENGINE_MODE", "local"))
            self._neural_client = NeuralEngineClient(base_url=teacher_url, mode=teacher_mode)
        return self._neural_client
    
    def analyze_system_gaps(self) -> List[Dict[str, str]]:
        """Analyze what capabilities are missing from the agent fleet.
        
        Checks existing agents against known system needs and returns
        a list of gaps that could be filled by new agents.
        """
        # Current capabilities from registry
        existing_caps = set()
        existing_roles = set()
        for agent in self._generated_agents:
            existing_roles.add(agent.get("role", ""))
            for cap in agent.get("capabilities", []):
                existing_caps.add(cap)
        
        # Known system needs (expandable)
        system_needs = [
            {
                "role": "performance_profiler",
                "description": "Profile Python code performance and identify slow functions",
                "capabilities": ["PROFILE_CODE", "IDENTIFY_BOTTLENECKS"],
                "reason": "Code refactoring needs performance data to prioritize"
            },
            {
                "role": "dependency_auditor",
                "description": "Audit Python dependencies for vulnerabilities and updates",
                "capabilities": ["AUDIT_DEPS", "CHECK_VULNERABILITIES"],
                "reason": "Security requires knowing dependency health"
            },
            {
                "role": "test_runner",
                "description": "Run tests and report results for evolution validation",
                "capabilities": ["RUN_TESTS", "REPORT_COVERAGE"],
                "reason": "Evolution pipeline needs test feedback for canary validation"
            },
            {
                "role": "backup_agent",
                "description": "Manage system backups and ensure data recovery capability",
                "capabilities": ["CREATE_BACKUP", "VERIFY_BACKUP"],
                "reason": "System resilience requires automated backups"
            },
        ]
        
        gaps = []
        for need in system_needs:
            role = need["role"]
            # Skip if role already registered
            if role in existing_roles:
                continue
            # Skip if agent file already exists on disk
            agent_file = self.agents_dir / f"{role}_agent.py"
            if agent_file.exists():
                continue
            # v5.1: Skip if role has a built-in blueprint (handled by spawn phase)
            if role in self.BUILTIN_BLUEPRINTS:
                continue
            gaps.append(need)
        
        return gaps
    
    async def design_agent_with_brain(self, gap: Dict[str, str]) -> Optional[AgentBlueprint]:
        """Ask the Brain (Teacher LLM) to design an agent blueprint.
        
        Takes a gap analysis dict with role, description, capabilities, reason
        and asks the Brain to design handler implementations.
        
        Returns an AgentBlueprint ready for code generation, or None if failed.
        """
        client = self._get_brain_client()
        
        role = gap["role"]
        description = gap["description"]
        capabilities = gap.get("capabilities", [])
        reason = gap.get("reason", "System capability gap")
        
        # v10: Retry limit — skip roles that failed 3+ times
        try:
            failure_file = Path(__file__).parent / "agent_failures.jsonl"
            role_failure_count = 0
            if failure_file.exists():
                with open(failure_file) as ff:
                    for line in ff:
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            rec = json.loads(line)
                            if rec.get("role") == role:
                                role_failure_count += 1
                        except Exception:
                            pass
            if role_failure_count >= 3:
                logger.warning(f"\U0001f6d1 Skipping {role}: {role_failure_count} failures (limit=3)")
                return None
        except Exception:
            pass
        
        # Build class name from role
        class_name = "".join(word.capitalize() for word in role.split("_")) + "Agent"
        
        # Build the prompt
        prompt = f"""Design a Python agent for the NOOGH system.

Agent: {class_name}
Role: {role}
Purpose: {description}
Capabilities: {', '.join(capabilities)}

The agent must follow this contract:
1. Inherit from AgentWorker
2. __init__ must call super().__init__(role, custom_handlers)
3. Each handler is an async method: async def _handler_name(self, task: Dict[str, Any]) -> Dict[str, Any]
4. Handlers receive task with arguments in task.get("arguments", {{}})
5. Return {{"success": True/False, ...data...}}

Output ONLY a JSON object with this structure (no markdown, no explanation):
{{
    "handlers": [
        {{
            "name": "_method_name",
            "capability": "CAPABILITY_NAME",
            "description": "what it does",
            "body": "Python code for the handler body (indented with 12 spaces)"
        }}
    ],
    "risk_level": "SAFE or RESTRICTED",
    "extra_imports": ["optional additional imports"]
}}

RULES:
- Use only standard library + psutil (for system tasks)
- No eval(), exec(), or __import__()
- SAFE agents MUST NOT import: subprocess, shutil, ctypes, socket
- If you need file operations, use os.path and open() — NOT shutil
- If you need shell commands, set risk_level to RESTRICTED
- Keep each handler under 30 lines
- Return meaningful data in every handler"""

        # v5.1: Inject failure memory — teach Brain from past mistakes
        try:
            failure_file = Path(__file__).parent / "agent_failures.jsonl"
            if failure_file.exists():
                failures_for_role = []
                with open(failure_file) as ff:
                    for line in ff:
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            rec = json.loads(line)
                            if rec.get("role") == role:
                                failures_for_role.append(rec)
                        except Exception:
                            pass
                
                if failures_for_role:
                    failure_warnings = []
                    for f in failures_for_role[-3:]:
                        violations = f.get("violations", [])
                        failure_warnings.append(f"  - {'; '.join(violations)}")
                    
                    # v10: Inject actual violations instead of hardcoded warning
                    prompt += (
                        f"\n\n\u26a0\ufe0f CRITICAL — Previous attempts for this agent were REJECTED:\n"
                        + "\n".join(failure_warnings) +
                        f"\n\nYou MUST avoid ALL of the above violations. "
                        f"Do NOT repeat any of these patterns."
                    )
                    logger.info(f"\U0001f4da Injected {len(failures_for_role)} failure memories for {role}")
        except Exception as e:
            logger.debug(f"Failure memory injection skipped: {e}")

        # 🌐 Enrich prompt with web research (non-blocking, best-effort)
        try:
            from .brain_web import research_topic, build_research_prompt_section
            research_query = f"Python {role.replace('_', ' ')} agent best practices"
            research = await research_topic(research_query, depth=1)
            research_context = build_research_prompt_section(research)
            if research_context:
                prompt += f"\n\nReference material from the web:\n{research_context}"
                logger.info(f"🌐 Web research enriched prompt for {role}")
        except Exception as e:
            logger.debug(f"Web research skipped for {role}: {e}")

        messages = [
            {
                "role": "system",
                "content": (
                    "You are an expert Python engineer designing autonomous agents. "
                    "Output ONLY valid JSON, no markdown fences, no explanation."
                )
            },
            {
                "role": "user",
                "content": prompt
            }
        ]
        
        try:
            # v10: Lower temperature for agent design (precision > creativity)
            original_temp = getattr(client, '_vllm_temperature', 0.7)
            client._vllm_temperature = 0.3
            result = await client.complete(messages, max_tokens=2048)
            client._vllm_temperature = original_temp
            
            if not result.get("success") or not result.get("content"):
                logger.warning(f"Brain returned no content for {role}")
                return None
            
            # Parse the JSON response
            response = result["content"].strip()
            
            # Clean markdown fences if present
            if response.startswith("```"):
                lines = response.splitlines()
                response = "\n".join(
                    l for l in lines 
                    if not l.strip().startswith("```")
                )
            
            spec = json.loads(response)
            
            # Build handlers list
            handlers = []
            for h in spec.get("handlers", []):
                handlers.append({
                    "name": h["name"],
                    "description": h.get("description", ""),
                    "capability": h["capability"],
                    "body": h.get("body", '            return {"success": True}')
                })
            
            if not handlers:
                logger.warning(f"Brain designed 0 handlers for {role}")
                return None
            
            # Create blueprint
            blueprint = AgentBlueprint(
                agent_id=f"brain_{role}_{int(time.time())}",
                name=class_name,
                role=role,
                description=description,
                capabilities=capabilities,
                handlers=handlers,
                risk_level=spec.get("risk_level", "SAFE"),
                reason=reason
            )
            
            logger.warning(
                f"🧠 Brain designed blueprint: {class_name} "
                f"({len(handlers)} handlers, risk={blueprint.risk_level})"
            )
            
            # 📚 Record for distillation (Teacher → Student training)
            try:
                from .distillation_collector import get_distillation_collector
                collector = get_distillation_collector()
                collector.record_agent_design(
                    prompt=prompt,
                    response=response,
                    agent_name=class_name,
                    role=role,
                    capabilities=capabilities,
                )
            except Exception as dist_err:
                logger.debug(f"Distillation recording skipped: {dist_err}")
            
            return blueprint
            
        except json.JSONDecodeError as e:
            logger.warning(f"Brain returned invalid JSON for {role}: {e}")
            return None
        except Exception as e:
            logger.error(f"Brain agent design failed for {role}: {e}")
            return None


# ============================================================
#  Singleton
# ============================================================

_factory_instance: Optional[AgentFactory] = None

def get_agent_factory() -> AgentFactory:
    """Get the global AgentFactory instance."""
    global _factory_instance
    if _factory_instance is None:
        _factory_instance = AgentFactory()
    return _factory_instance
