"""
Decision Scorer - Keyword-Based Action Selection

Selects actions using keyword matching and weighted random selection.

MECHANISM DISCLOSURE:
- Candidates generated by keyword overlap, not semantic understanding
- Action types are template strings: f"act_on_{belief_id}"
- Selection uses weighted random (cryptographic PRNG)
- "Constraints" are score penalties, not blocks
- Persistence is filesystem-based and MAY BE LOST
"""

import hashlib
import logging
import os
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set, Tuple
from enum import Enum

logger = logging.getLogger("unified_core.core.gravity")


class DecisionType(Enum):
    """Types of decisions the system can make."""
    ACTION = "action"          # Execute an action
    GOAL = "goal"              # Adopt a new goal
    BELIEF = "belief"          # Adopt a new belief
    ABSTAIN = "abstain"        # Explicitly do nothing


@dataclass
class DecisionContext:
    """
    Context provided for decision-making.
    """
    query: str                 # What needs to be decided
    constraints: Dict[str, Any] = field(default_factory=dict)
    urgency: float = 0.5       # 0.0 to 1.0
    timestamp: float = field(default_factory=time.time)


@dataclass
class Goal:
    """
    A goal synthesized from the world model.
    Not selected from a list — GENERATED.
    """
    goal_id: str
    description: str
    derived_from_beliefs: List[str]
    derived_from_discrepancy: str
    priority: float = 0.5
    created_at: float = field(default_factory=time.time)
    committed: bool = False    # Once True, goal is permanent
    fingerprint: str = ""      # Semantic hash for deduplication

    def to_dict(self) -> Dict[str, Any]:
        return {
            "goal_id": self.goal_id,
            "description": self.description,
            "derived_from_beliefs": self.derived_from_beliefs,
            "derived_from_discrepancy": self.derived_from_discrepancy,
            "priority": self.priority,
            "created_at": self.created_at,
            "committed": self.committed,
            "fingerprint": self.fingerprint
        }


@dataclass
class ActionProposal:
    """
    A proposed action with fragility analysis and friction gate.
    
    MECHANISM DISCLOSURE:
    - fragility = how much the decision changes if top beliefs are inverted
    - High fragility + high impact → requires acknowledgment + delay
    """
    description: str
    confidence: float                       # Score from weighted selection
    fragility: float = 0.0                  # How unstable is this decision?
    requires_acknowledgment: bool = False   # Must user explicitly approve?
    friction_delay_seconds: float = 0.0     # Mandatory delay before execution
    mechanism_disclosure: str = ""          # Explanation of how decision was made
    
    def apply_friction_policy(self, impact_level: float = 0.5):
        """Apply friction based on fragility and impact."""
        if self.fragility > 0.6 or impact_level > 0.7:
            self.requires_acknowledgment = True
        if self.fragility > 0.4 and impact_level > 0.5:
            self.friction_delay_seconds = max(5.0, self.fragility * 15)


@dataclass
class Decision:
    """
    A decision record (advisory, not enforcing).
    
    HONESTY DISCLAIMER:
    - "Irreversible" refers to record keeping, not real-world effects
    - Decisions are suggestions that may be ignored
    """
    decision_id: str
    decision_type: DecisionType
    content: Dict[str, Any]                # The decision content
    commitment_hash: str                   # Proof this decision was made
    based_on_beliefs: List[str]            # Beliefs that informed this
    constrained_by: List[str]              # Constraints that shaped this
    cost_paid: float                       # Penalties absorbed
    fragility: float = 0.0                 # NEW: How fragile is this decision?
    made_at: float = field(default_factory=time.time)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "decision_id": self.decision_id,
            "decision_type": self.decision_type.value,
            "content": self.content,
            "commitment_hash": self.commitment_hash,
            "based_on_beliefs": self.based_on_beliefs,
            "constrained_by": self.constrained_by,
            "cost_paid": self.cost_paid,
            "fragility": self.fragility,
            "made_at": self.made_at
        }



class DecisionScorer:
    """
    Keyword-based action selection with weighted random output.
    
    MECHANISM DISCLOSURE:
    - Candidates are generated by keyword overlap, not semantic understanding
    - Selection uses weighted random (cryptographic PRNG)
    - "Constraints" are score penalties, not blocks
    - All decisions are logged but enforcement is advisory only
    
    The former name "GravityWell" implied authority that does not exist.
    """
    
    def __init__(
        self,
        world_model=None,
        memory=None,
        consequence_engine=None,
        scar_tissue=None
    ):
        self._world = world_model
        self._memory = memory
        self._consequences = consequence_engine
        self._scars = scar_tissue
        
        # Auto-wire missing dependencies
        self._auto_wire()
        
        self._decision_counter = 0
        self._decision_history: List[Decision] = []
        self._active_goals: Dict[str, Goal] = {}
        self._goal_fingerprints: Set[str] = set()
        
        # 🧠 DECISION MEMORY
        self._decision_cache: Dict[str, Decision] = {}
        self._decision_cache_ttl = 300
        self._decision_timestamps: Dict[str, float] = {}
        
        # NeuronFabric + EventBus
        self._neuron_fabric = None
        self._event_bus = None
        try:
            from unified_core.core.neuron_fabric import get_neuron_fabric
            self._neuron_fabric = get_neuron_fabric()
        except Exception:
            pass
        try:
            from unified_core.integration.event_bus import get_event_bus
            self._event_bus = get_event_bus()
        except Exception:
            pass
        
        logger.info("DecisionScorer initialized with auto-wiring + semantic activation")
    
    def _auto_wire(self):
        """Auto-wire missing dependencies from known singletons."""
        if not self._world:
            try:
                from unified_core.core.world_model import WorldModel
                self._world = WorldModel()
            except Exception:
                pass
        if not self._consequences:
            try:
                from unified_core.core.consequence import ConsequenceEngine
                self._consequences = ConsequenceEngine()
            except Exception:
                pass
        if not self._scars:
            try:
                from unified_core.core.scar import FailureRecord
                self._scars = FailureRecord(enable_enforcement=True)
            except Exception:
                pass
    
    def set_world_model(self, world_model):
        """Set WorldModel reference."""
        self._world = world_model
    
    def set_memory(self, memory):
        """Set CoerciveMemory reference."""
        self._memory = memory
    
    def set_consequence_engine(self, engine):
        """Set ConsequenceEngine reference."""
        self._consequences = engine
    
    def set_scar_tissue(self, scars):
        """Set ScarTissue reference."""
        self._scars = scars
    
    async def decide(self, context: DecisionContext) -> Decision:
        """
        Generate decision under genuine uncertainty (Async).
        
        Process:
        0. CHECK CACHE for similar recent decisions (FAST PATH)
        1. Query world model for belief state
        2. Generate candidate actions from beliefs (not templates)
        3. Filter candidates through memory (blocks, penalties)
        4. Check consequence constraints
        5. Select action under uncertainty (not epsilon-greedy)
        6. COMMIT decision to consequence engine (irreversible)
        7. Return decision with commitment hash
        """
        # 0. Fast Path: Cache check
        cached = self._check_decision_cache(context)
        if cached:
            return cached
        
        # 1. Initialize decision state
        decision_id, usable_beliefs = await self._init_decision(context)
        
        # 2. Generate candidate actions
        candidates = self._match_keywords_to_templates(context, usable_beliefs)
        
        # 3 & 4. Filter candidates through memory and consequences
        filtered_candidates, constraints_applied, total_cost = self._filter_candidates(
            candidates, context
        )
        
        # 5. Select action
        selected = self._weighted_random_selection(
            filtered_candidates, 
            usable_beliefs,
            context.urgency
        )
        
        # 6. Finalize and record
        return self._finalize_decision(
            decision_id, context, selected, constraints_applied, total_cost
        )

    async def _init_decision(self, context: DecisionContext) -> Tuple[str, List]:
        """Prepare decision ID and query world model for beliefs."""
        self._decision_counter += 1
        decision_id = hashlib.sha256(
            f"decision:{self._decision_counter}:{context.query}:{time.time()}".encode()
        ).hexdigest()[:16]
        
        usable_beliefs = await self._world.get_usable_beliefs() if self._world else []
        return decision_id, usable_beliefs

    def _finalize_decision(
        self, 
        decision_id: str, 
        context: DecisionContext, 
        selected: Optional[Dict[str, Any]],
        constraints_applied: List[str],
        total_cost: float
    ) -> Decision:
        """Commit the decision and create the persistent record."""
        if not selected:
            selected = {
                "action_type": "abstain", 
                "params": {"reason": "all_blocked_or_empty"}, 
                "belief_ids": []
            }
            decision_type = DecisionType.ABSTAIN
        else:
            decision_type = DecisionType.ACTION
        
        # COMMIT decision to consequence engine
        commitment_hash = self._commit_decision(decision_id, selected)
        
        # Create record
        decision = Decision(
            decision_id=decision_id,
            decision_type=decision_type,
            content=selected,
            commitment_hash=commitment_hash,
            based_on_beliefs=selected.get("belief_ids", []),
            constrained_by=constraints_applied,
            cost_paid=total_cost
        )
        
        # Cache management
        self._decision_history.append(decision)
        query_hash = hashlib.sha256(context.query.encode()).hexdigest()[:16]
        self._decision_cache[query_hash] = decision
        self._decision_timestamps[query_hash] = time.time()
        
        # Publish decision event via EventBus
        if self._event_bus:
            try:
                from unified_core.integration.event_bus import StandardEvents, EventPriority
                self._event_bus.publish_sync(
                    StandardEvents.DECISION_COMMITTED,
                    {
                        "decision_id": decision_id,
                        "decision_type": decision_type.value,
                        "action_type": selected.get("action_type", "unknown"),
                        "commitment_hash": commitment_hash,
                        "cost": total_cost,
                    },
                    "DecisionScorer",
                    EventPriority.NORMAL
                )
            except Exception as e:
                logger.debug(f"Failed to publish decision event: {e}")
        
        return decision

    def _check_decision_cache(self, context: DecisionContext) -> Optional[Decision]:
        """Check if a similar decision is already cached and valid."""
        query_hash = hashlib.sha256(context.query.encode()).hexdigest()[:16]
        cached_timestamp = self._decision_timestamps.get(query_hash, 0)
        
        if time.time() - cached_timestamp < self._decision_cache_ttl:
            cached = self._decision_cache.get(query_hash)
            if cached:
                logger.info(f"⚡ CACHED DECISION: {cached.decision_id} (skipped {self._decision_cache_ttl}s computation)")
                return cached
        return None

    def _filter_candidates(
        self, 
        candidates: List[Dict[str, Any]], 
        context: DecisionContext
    ) -> Tuple[List[Dict[str, Any]], List[str], float]:
        """Filter candidates through memory, consequences, and scars."""
        filtered = []
        applied = []
        total_cost = 0.0
        
        for candidate in candidates:
            cost = self._calculate_decision_cost(
                action_type=candidate["action_type"],
                urgency=context.urgency,
                belief_confidence=candidate.get("confidence", 0.5),
                constraints_count=0
            )
            
            # 1. Memory check
            if self._memory:
                from .coercive_memory import MemoryVerdict
                verdict = self._memory.check(candidate["action_type"], candidate.get("params", {}))
                if verdict == MemoryVerdict.DISCOURAGED:
                    applied.append(f"blocked:{candidate['action_type']}")
                    continue
                if verdict == MemoryVerdict.PENALIZED:
                    cost += self._memory.get_total_cost(candidate["action_type"])
            
            # 2. Consequence check
            if self._consequences:
                from .consequence import Action
                action = Action(action_type=candidate["action_type"], parameters=candidate.get("params", {}))
                blocked, b_hash = self._consequences.is_action_blocked(action)
                if blocked:
                    applied.append(f"consequence:{b_hash}")
                    continue
            
            # 3. Scar check
            if self._scars and self._scars.is_action_blocked(candidate["action_type"]):
                applied.append(f"scar_enforced:{candidate['action_type']}")
                continue
            
            total_cost += cost
            filtered.append(candidate)
            
        return filtered, applied, total_cost

    def _commit_decision(self, decision_id: str, selected: Dict[str, Any]) -> str:
        """Commit selected action to consequence engine and return commitment hash."""
        now = time.time()
        commitment_hash = hashlib.sha256(
            f"commit:{decision_id}:{selected['action_type']}:{now}:{os.urandom(8).hex()}".encode()
        ).hexdigest()
        
        if self._consequences:
            from .consequence import Action, Outcome
            action = Action(action_type=selected["action_type"], parameters=selected.get("params", {}))
            outcome = Outcome(success=True, result={"decided": True})
            self._consequences.commit(action, outcome)
            
        return commitment_hash
    
    def _match_keywords_to_templates(
        self, 
        context: DecisionContext, 
        beliefs: List
    ) -> List[Dict[str, Any]]:
        """
        Generate candidate actions by keyword matching.
        """
        # Extract keywords from context query
        query_words = set(context.query.lower().split())
        
        # 1. Generate candidates from usable beliefs
        candidates = self._generate_belief_candidates(query_words, beliefs)
        
        # 2. Add context-derived candidate
        if context.query:
            context_id = hashlib.sha256(context.query.encode()).hexdigest()[:8]
            candidates.append({
                "action_type": f"respond_to_{context_id}",
                "params": {"query": context.query},
                "belief_ids": [],
                "score": context.urgency
            })
        
        return candidates

    def _generate_belief_candidates(self, query_words: Set[str], beliefs: List) -> List[Dict[str, Any]]:
        """Generate candidates using NeuronFabric semantic activation (falls back to keywords)."""
        candidates = []
        
        # Try NeuronFabric semantic matching first
        semantic_matches = {}
        if self._neuron_fabric:
            try:
                query = " ".join(query_words)
                if query.strip():
                    result = self._neuron_fabric.activate_with_attention(
                        context=query, top_k=15, min_relevance=0.1
                    )
                    if isinstance(result, dict):
                        semantic_matches = result.get("activations", result)
                    else:
                        semantic_matches = result if result else {}
            except Exception as e:
                logger.debug(f"Semantic activation failed, keyword fallback: {e}")
        
        for belief in beliefs:
            if not belief.is_usable():
                continue
            
            prop_text = str(belief.proposition)
            prop_words = set(prop_text.lower().split())
            keyword_relevance = len(query_words & prop_words)
            
            # Semantic boost from NeuronFabric
            semantic_boost = 0.0
            for nid, activation in semantic_matches.items():
                n = self._neuron_fabric.get_neuron(nid) if self._neuron_fabric else None
                if n and hasattr(n, 'metadata') and n.metadata.get('belief_id') == belief.belief_id:
                    semantic_boost = activation * 0.5
                    break
            
            relevance = keyword_relevance + semantic_boost
            
            if relevance > 0 or belief.confidence > 0.7:
                action_type = f"act_on_{belief.belief_id[:8]}"
                candidates.append({
                    "action_type": action_type,
                    "params": {
                        "source_belief": belief.belief_id,
                        "proposition": belief.proposition,
                        "confidence": belief.confidence,
                        "relevance": relevance
                    },
                    "belief_ids": [belief.belief_id],
                    "score": belief.confidence * (1 + relevance * 0.3)
                })
        return candidates

    def _weighted_random_selection(
        self,
        candidates: List[Dict[str, Any]],
        beliefs: List,
        urgency: float
    ) -> Optional[Dict[str, Any]]:
        """
        Select action via modularized WEIGHTED RANDOM.
        """
        if not candidates:
            return None
        
        # 1. Calculate selection weights
        weights = self._calculate_selection_weights(candidates, urgency)
        
        # 2. Perform selection
        if sum(weights) == 0:
            return candidates[0]
            
        return self._perform_weighted_selection(candidates, weights)

    def _calculate_selection_weights(self, candidates: List[Dict[str, Any]], urgency: float) -> List[float]:
        """Calculate weights for candidates adjusted for urgency and scars."""
        weights = []
        for candidate in candidates:
            base_score = candidate.get("score", 0.5)
            
            # Adjust for high pressure
            if urgency > 0.7:
                base_score *= 1.5
            
            # Adjust for scar depth
            if self._scars:
                scar_depth = self._scars.get_scar_depth()
                penalty = min(scar_depth * 0.1, 0.3)
                base_score -= penalty
            
            weights.append(max(0.0, base_score))
        return weights

    def _perform_weighted_selection(self, candidates: List[Dict[str, Any]], weights: List[float]) -> Dict[str, Any]:
        """Perform the actual selection using cryptographic PRNG."""
        import secrets
        total = sum(weights)
        normalized = [w / total for w in weights]
        
        r = secrets.SystemRandom().random()
        cumulative = 0.0
        for i, weight in enumerate(normalized):
            cumulative += weight
            if r <= cumulative:
                return candidates[i]
        
        return candidates[-1]
    
    def compute_fragility(
        self,
        candidates: List[Dict[str, Any]],
        beliefs: List,
        selected_index: int
    ) -> float:
        """
        Compute decision fragility using real belief states.
        
        Analyzes actual confidence and falsification history.
        No mutation of belief objects.
        
        Returns: fragility score 0.0 (stable) to 1.0 (unstable)
        """
        if not beliefs or len(candidates) <= 1:
            return 0.0
        
        sorted_beliefs = sorted(beliefs, key=lambda b: b.confidence, reverse=True)[:3]
        weak_count = 0
        
        for belief in sorted_beliefs:
            conf = belief.confidence
            state = getattr(belief, 'state', 'active')
            state_str = state.value if hasattr(state, 'value') else str(state)
            
            if conf < 0.3 or conf > 0.9 or state_str in ('weakened', 'falsified'):
                weak_count += 1
        
        # Falsification penalty from real store
        falsification_penalty = 0.0
        if self._world and hasattr(self._world, '_memory'):
            store = self._world._memory
            if hasattr(store, '_get_all_falsifications_sync'):
                try:
                    falsifications = store._get_all_falsifications_sync()
                    recent = [f for f in falsifications if f.get('timestamp', 0) > time.time() - 3600]
                    falsification_penalty = min(len(recent) * 0.05, 0.3)
                except Exception:
                    pass
        
        fragility = (weak_count / max(len(sorted_beliefs), 1)) + falsification_penalty
        return min(fragility, 1.0)
    
    def _calculate_decision_cost(self, action_type: str, urgency: float, 
                                 belief_confidence: float, constraints_count: int) -> float:
        """
        Calculate real cost of a decision.
        
        Factors:
        - Base cost: 1.0
        - Urgency multiplier: Higher urgency = higher cost (pressure)
        - Confidence penalty: Low confidence = higher cost (risk)
        - Constraint overhead: Each constraint adds cost
        
        Returns: cost in arbitrary units (0.0+)
        """
        base_cost = 1.0
        
        # Urgency multiplier (0.5x to 2.0x)
        urgency_multiplier = 0.5 + (urgency * 1.5)
        
        # Confidence penalty (high confidence = low penalty)
        confidence_penalty = (1.0 - belief_confidence) * 2.0
        
        # Constraint overhead
        constraint_cost = constraints_count * 0.5
        
        total_cost = base_cost * urgency_multiplier + confidence_penalty + constraint_cost
        
        return max(0.0, total_cost)
    
    def _compute_goal_fingerprint(self, description: str) -> str:
        """
        Create semantic fingerprint for goal deduplication.
        
        Extracts key concepts from description and creates a stable hash.
        This prevents duplicate goals like "Verify: User inputs may contain malicious..."
        """
        # Normalize description
        normalized = description.lower().strip()
        
        # Remove common prefixes to focus on core concept
        for prefix in ["verify or strengthen:", "verify:", "strengthen:", "gather", "explore"]:
            if normalized.startswith(prefix):
                normalized = normalized[len(prefix):].strip()
        
        # Extract key words (remove stop words)
        stop_words = {"the", "a", "an", "and", "or", "but", "in", "on", "at", "to", "for", 
                      "of", "with", "by", "from", "may", "can", "will", "is", "are", "was"}
        words = [w for w in normalized.split() if w not in stop_words and len(w) > 2]
        
        # Sort words for stability (different word order = same fingerprint)
        concept = " ".join(sorted(words[:5]))  # Use top 5 key words
        
        # Hash the concept
        return hashlib.sha256(concept.encode()).hexdigest()[:16]
    
    async def generate_goals(self) -> List[Goal]:
        """
        Synthesize goals from world model asynchronously (v3.3.1-Alpha).
        """
        if not self._world:
            return []
            
        # 1. Collect proposals from different synthesis paths
        beliefs = await self._world.get_usable_beliefs()
        proposals = self._collect_goal_proposals(beliefs)
        
        # 2. Process and filter the proposal queue
        return self._process_goal_queue(proposals)

    def _collect_goal_proposals(self, beliefs: List) -> List[Goal]:
        """Aggregate candidates from discrepancy and gap analysis."""
        return self._find_goal_discrepancies(beliefs) + self._find_goal_gaps(beliefs)

    def _process_goal_queue(self, proposals: List[Goal]) -> List[Goal]:
        """Filter, deduplicate, and commit goal proposals."""
        generated_goals = []
        duplicate_count = 0
        
        for goal in proposals:
            # A. Deduplication
            if goal.fingerprint in self._goal_fingerprints:
                duplicate_count += 1
                continue
                
            # B. Architectural Authority (Scar Filtering)
            if self._scars and self._is_goal_restricted(goal):
                logger.info(f"Goal blocked by authority scar: {goal.description[:30]}")
                continue
                
            # C. Transactional Commitment
            self._commit_goal(goal)
            generated_goals.append(goal)
            
        if duplicate_count > 0:
            logger.info(f"Goal synthesis complete: {len(generated_goals)} new, {duplicate_count} duplicates prevented")
            
        return generated_goals

    def _commit_goal(self, goal: Goal):
        """Register the goal in the active tracking set."""
        goal.committed = True
        self._active_goals[goal.goal_id] = goal
        self._goal_fingerprints.add(goal.fingerprint)
        logger.info(f"Goal COMMITTED: {goal.goal_id} - {goal.description[:50]}")

    def _find_goal_discrepancies(self, beliefs: List) -> List[Goal]:
        """Identify discrepancies (beliefs with low confidence)."""
        proposals = []
        for belief in beliefs:
            if belief.confidence < 0.5:
                description = f"Verify or strengthen: {belief.proposition}"
                fingerprint = self._compute_goal_fingerprint(description)
                goal_id = hashlib.sha256(f"goal:verify:{belief.belief_id}:{time.time()}".encode()).hexdigest()[:16]
                
                proposals.append(Goal(
                    goal_id=goal_id,
                    description=description,
                    derived_from_beliefs=[belief.belief_id],
                    derived_from_discrepancy=f"Low confidence ({belief.confidence:.2f})",
                    priority=1.0 - belief.confidence,
                    fingerprint=fingerprint
                ))
        return proposals

    def _find_goal_gaps(self, beliefs: List) -> List[Goal]:
        """Identify gaps (insufficient beliefs)."""
        if len(beliefs) >= 3:
            return []
            
        description = "Gather more observations to form new beliefs"
        fingerprint = self._compute_goal_fingerprint(description)
        goal_id = hashlib.sha256(f"goal:explore:{time.time()}".encode()).hexdigest()[:16]
        
        return [Goal(
            goal_id=goal_id,
            description=description,
            derived_from_beliefs=[],
            derived_from_discrepancy="Insufficient beliefs for decision-making",
            priority=0.8,
            fingerprint=fingerprint
        )]

    def _is_goal_restricted(self, goal: Goal) -> bool:
        """Check if any restricted keyword appears in the goal description."""
        if not (self._scars and goal.description):
            return False
            
        desc_lower = goal.description.lower()
        return any(pattern in desc_lower for pattern in self._scars.get_restricted_actions())
    
    def get_decision_count(self) -> int:
        """Return total decisions made. Only grows."""
        return self._decision_counter
    
    def get_active_goals(self) -> Dict[str, Goal]:
        """Return currently active goals."""
        return self._active_goals.copy()

    def resolve_goal(self, goal_id: str):
        """Phase 22: Goal Resolution - Remove from active tracking."""
        if goal_id in self._active_goals:
            goal = self._active_goals.pop(goal_id)
            if goal.fingerprint in self._goal_fingerprints:
                self._goal_fingerprints.remove(goal.fingerprint)
            logger.info(f"Goal RESOLVED: {goal_id} - {goal.description[:50]}")
            return True
        return False

    def resolve_goal_by_description(self, description: str) -> bool:
        """Resolve an active goal by its description string."""
        for goal_id, goal in list(self._active_goals.items()):
            if goal.description == description:
                return self.resolve_goal(goal_id)
        return False

    def clear_active_goals(self):
        """Emergency cleanup of all active goals."""
        count = len(self._active_goals)
        self._active_goals.clear()
        self._goal_fingerprints.clear()
        logger.warning(f"Cleared {count} active goals from DecisionScorer memory.")
    
    def is_predictable(self) -> bool:
        """
        Self-test for predictability.
        Should return False if architecture is correct.
        """
        # The architecture includes:
        # - Belief state (changes over time)
        # - Memory penalties (accumulate)
        # - Scar depth (only increases)
        # - Random selection component in _weighted_random_selection
        # - Consequence constraints (grow)
        #
        # Even with full code access, exact decision cannot be predicted
        # because internal state is hidden and non-deterministic selection exists
        return False


# === STRICT DEPRECATION ===
# Backward compatibility with enforced honesty
def _deprecated_alias(old_name, new_name, new_class):
    """Create a deprecated alias that warns or errors based on strictness."""
    import warnings
    import os
    
    msg = f"{old_name} is deprecated. Use {new_name}. This alias will be removed in next version."
    
    if os.getenv("NOOGH_STRICT_MODE") == "1":
        raise RuntimeError(msg)
    
    warnings.warn(msg, DeprecationWarning, stacklevel=3)
    return new_class


class _DeprecatedGravityWell:
    """Deprecated wrapper that warns on instantiation."""
    def __new__(cls, *args, **kwargs):
        return _deprecated_alias("GravityWell", "DecisionScorer", DecisionScorer)(*args, **kwargs)


# Backward compatibility alias (with warning)
GravityWell = _DeprecatedGravityWell
