"""
NOOGH BackupAgentAgent

Auto-generated agent by AgentFactory v1.0
Purpose: Manage system backups and ensure data recovery capability
Generated: 2026-02-16 23:58:54
Reason: System resilience requires automated backups
"""

import asyncio
import logging
from typing import Dict, Any

from unified_core.orchestration.agent_worker import AgentWorker
from unified_core.orchestration.messages import AgentRole

logger = logging.getLogger("agents.backup_agent")


class BackupAgentAgent(AgentWorker):
    """
    Manage system backups and ensure data recovery capability
    
    Capabilities:
    - CREATE_BACKUP
    - VERIFY_BACKUP
    
    Auto-generated by NOOGH AgentFactory.
    """
    
    def __init__(self):
        custom_handlers = {
            "CREATE_BACKUP": self._create_backup,
            "VERIFY_BACKUP": self._verify_backup,
        }
        
        # Use dynamic role registration
        role = AgentRole("backup_agent")
        super().__init__(role, custom_handlers)
        logger.info("✅ BackupAgentAgent initialized")
    
    async def _create_backup(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """
        Creates a backup of specified directories
        
        Capability: CREATE_BACKUP
        """
        try:
            arguments = task.get("arguments", {})
            
            src = task.get("arguments", {}).get("source_dir")
            dst = task.get("arguments", {}).get("dest_dir")
            if not src or not dst:
                return {"success": False, "error": "Missing source/destination"}
            import os, shutil
            import asyncio
            try:
                await asyncio.to_thread(shutil.copytree, src, dst, dirs_exist_ok=True)
                file_count = await asyncio.to_thread(lambda: sum(len(f) for _, _, f in os.walk(dst)))
                return {"success": True, "message": f"Backup created: {file_count} files"}
            except Exception as e:
                return {"success": False, "error": str(e)}
            
        except Exception as e:
            logger.error(f"_create_backup failed: {e}")
            return {"success": False, "error": str(e)}

    async def _verify_backup(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """
        Verifies backup integrity by comparing file counts
        
        Capability: VERIFY_BACKUP
        """
        try:
            arguments = task.get("arguments", {})
            
            src = task.get("arguments", {}).get("source_dir")
            dst = task.get("arguments", {}).get("dest_dir")
            if not src or not dst:
                return {"success": False, "error": "Missing source/destination"}
            import os
            import asyncio
            try:
                src_count = await asyncio.to_thread(lambda: sum(len(f) for _, _, f in os.walk(src)))
                dst_count = await asyncio.to_thread(lambda: sum(len(f) for _, _, f in os.walk(dst)))
                match = src_count == dst_count
                return {"success": True, "verified": match, "src_files": src_count, "dst_files": dst_count}
            except Exception as e:
                return {"success": False, "error": str(e)}
            
        except Exception as e:
            logger.error(f"_verify_backup failed: {e}")
            return {"success": False, "error": str(e)}



# ============================================================
# Entry Point
# ============================================================

async def main():
    """Start the BackupAgentAgent."""
    logger.info("🚀 Starting BackupAgentAgent...")
    agent = BackupAgentAgent()
    agent.start()
    
    try:
        while True:
            await asyncio.sleep(1)
    except KeyboardInterrupt:
        logger.info("🛑 BackupAgentAgent stopping...")


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    asyncio.run(main())
