"""NOOGH HealthMonitorAgent — Auto-generated by AgentFactory v1.0

Purpose: System health monitoring and alerting
Generated: 2026-02-14
"""

import asyncio
import logging
from typing import Dict, Any

from unified_core.orchestration.agent_worker import AgentWorker
from unified_core.orchestration.messages import AgentRole

logger = logging.getLogger("agents.health_monitor")


class HealthMonitorAgent(AgentWorker):
    """
    System health monitoring agent.
    
    Capabilities:
    - MONITOR_HEALTH: Check CPU, RAM, disk status
    - CHECK_SERVICES: Verify critical services are running
    
    Auto-generated by NOOGH AgentFactory.
    """
    
    def __init__(self):
        custom_handlers = {
            "MONITOR_HEALTH": self._monitor_health,
            "CHECK_SERVICES": self._check_services,
        }
        role = AgentRole("health_monitor")
        super().__init__(role, custom_handlers)
        logger.info("✅ HealthMonitorAgent initialized")
    
    async def _monitor_health(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """Check CPU, RAM, disk status."""
        try:
            import psutil
            import asyncio
            def _get_metrics():
                return {
                    "cpu": psutil.cpu_percent(interval=0.5),
                    "ram": psutil.virtual_memory().percent,
                    "disk": psutil.disk_usage("/").percent
                }
            metrics = await asyncio.to_thread(_get_metrics)
            cpu, ram, disk = metrics["cpu"], metrics["ram"], metrics["disk"]
            
            alerts = []
            if cpu > 90:
                alerts.append(f"CPU critical: {cpu}%")
            if ram > 85:
                alerts.append(f"RAM high: {ram}%")
            if disk > 90:
                alerts.append(f"Disk almost full: {disk}%")
            
            return {
                "success": True,
                "metrics": metrics,
                "alerts": alerts,
                "status": "critical" if alerts else "healthy"
            }
        except Exception as e:
            logger.error(f"_monitor_health failed: {e}")
            return {"success": False, "error": str(e)}
    
    async def _check_services(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """Verify critical services are running."""
        try:
            import asyncio
            services = ["noogh-agent", "redis-server"]
            results = {}
            for svc in services:
                try:
                    process = await asyncio.create_subprocess_exec(
                        "systemctl", "is-active", svc,
                        stdout=asyncio.subprocess.PIPE,
                        stderr=asyncio.subprocess.PIPE
                    )
                    try:
                        stdout_bytes, _ = await asyncio.wait_for(process.communicate(), timeout=5.0)
                        results[svc] = stdout_bytes.decode('utf-8').strip()
                    except asyncio.TimeoutError:
                        process.kill()
                        results[svc] = "timeout"
                except Exception:
                    results[svc] = "unknown"
            
            return {"success": True, "services": results}
        except Exception as e:
            logger.error(f"_check_services failed: {e}")
            return {"success": False, "error": str(e)}


# ============================================================
# Entry Point
# ============================================================

async def main():
    """Start the HealthMonitorAgent."""
    logger.info("🚀 Starting HealthMonitorAgent...")
    agent = HealthMonitorAgent()
    agent.start()
    
    try:
        while True:
            await asyncio.sleep(1)
    except KeyboardInterrupt:
        logger.info("🛑 HealthMonitorAgent stopping...")


if __name__ == "__main__":
    import sys
    if "--report" in sys.argv:
        import json
        async def run_report():
            agent = object.__new__(HealthMonitorAgent)
            res1 = await agent._monitor_health({})
            res2 = await agent._check_services({})
            print(json.dumps({"health": res1, "services": res2}, indent=2))
        asyncio.run(run_report())
        sys.exit(0)

    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    asyncio.run(main())
