"""
NOOGH PerformanceProfilerAgent

Auto-generated agent by AgentFactory v1.0
Purpose: Profile Python code performance and identify slow functions
Generated: 2026-02-16 23:58:54
Reason: Code refactoring needs performance data to prioritize
"""

import asyncio
import logging
from typing import Dict, Any

from unified_core.orchestration.agent_worker import AgentWorker
from unified_core.orchestration.messages import AgentRole

logger = logging.getLogger("agents.performance_profiler")


class PerformanceProfilerAgent(AgentWorker):
    """
    Profile Python code performance and identify slow functions
    
    Capabilities:
    - PROFILE_CODE
    - IDENTIFY_BOTTLENECKS
    
    Auto-generated by NOOGH AgentFactory.
    """
    
    def __init__(self):
        custom_handlers = {
            "PROFILE_CODE": self._profile_code,
            "IDENTIFY_BOTTLENECKS": self._identify_bottlenecks,
        }
        
        # Use dynamic role registration
        role = AgentRole("performance_profiler")
        super().__init__(role, custom_handlers)
        logger.info("✅ PerformanceProfilerAgent initialized")
    
    async def _profile_code(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """
        Profile Python code safely using cProfile with restricted globals
        
        Capability: PROFILE_CODE
        """
        try:
            arguments = task.get("arguments", {})
            
            code = task.get("arguments", {}).get("code")
            if not code:
                return {"success": False, "error": "No code provided"}
            
            safe_builtins = {
                "print": print, "len": len, "range": range,
                "int": int, "float": float, "str": str,
                "list": list, "dict": dict, "tuple": tuple,
                "set": set, "enumerate": enumerate, "zip": zip,
                "any": any, "all": all, "sum": sum,
                "min": min, "max": max, "abs": abs,
                "round": round, "pow": pow, "divmod": divmod,
                "isinstance": isinstance, "type": type,
                "sorted": sorted, "reversed": reversed,
                "open": None, "eval": None, "exec": None,
                "__import__": None, "compile": None,
            }
            safe_globals = {"__builtins__": safe_builtins}
            
            import cProfile, io, pstats
            pr = cProfile.Profile()
            pr.runctx(code, safe_globals, {})
            
            s = io.StringIO()
            ps = pstats.Stats(pr, stream=s).sort_stats("cumulative")
            ps.print_stats()
            return {"success": True, "performance_metrics": s.getvalue()}
            
        except Exception as e:
            logger.error(f"_profile_code failed: {e}")
            return {"success": False, "error": str(e)}

    async def _identify_bottlenecks(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """
        Parse cProfile output to find the slowest functions
        
        Capability: IDENTIFY_BOTTLENECKS
        """
        try:
            arguments = task.get("arguments", {})
            
            metrics = task.get("arguments", {}).get("performance_metrics", "")
            if not metrics:
                return {"success": False, "error": "No performance metrics"}
            
            lines = metrics.split("\n")
            bottlenecks = []
            in_stats = False
            for line in lines:
                if "ncalls" in line and "tottime" in line:
                    in_stats = True
                    continue
                if in_stats and line.strip():
                    parts = line.split()
                    if len(parts) >= 6:
                        try:
                            bottlenecks.append({
                                "function": parts[5],
                                "cumtime": float(parts[3]),
                                "calls": parts[0],
                            })
                        except (ValueError, IndexError):
                            pass
            
            bottlenecks.sort(key=lambda x: x["cumtime"], reverse=True)
            return {"success": True, "bottlenecks": bottlenecks[:10]}
            
        except Exception as e:
            logger.error(f"_identify_bottlenecks failed: {e}")
            return {"success": False, "error": str(e)}



# ============================================================
# Entry Point
# ============================================================

async def main():
    """Start the PerformanceProfilerAgent."""
    logger.info("🚀 Starting PerformanceProfilerAgent...")
    agent = PerformanceProfilerAgent()
    agent.start()
    
    try:
        while True:
            await asyncio.sleep(1)
    except KeyboardInterrupt:
        logger.info("🛑 PerformanceProfilerAgent stopping...")


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    asyncio.run(main())
