"""
NOOGH TestRunnerAgent

Auto-generated agent by AgentFactory v1.0
Purpose: Run tests and report results for evolution validation
Generated: 2026-02-15 01:06:51
Reason: Evolution pipeline needs test feedback for canary validation
"""

import asyncio
import logging
from typing import Dict, Any

from unified_core.orchestration.agent_worker import AgentWorker
from unified_core.orchestration.messages import AgentRole

logger = logging.getLogger("agents.test_runner")


class TestRunnerAgent(AgentWorker):
    """
    Run tests and report results for evolution validation
    
    Capabilities:
    - RUN_TESTS
    - REPORT_COVERAGE
    
    Auto-generated by NOOGH AgentFactory.
    """
    
    def __init__(self):
        custom_handlers = {
            "RUN_TESTS": self._run_tests,
            "REPORT_COVERAGE": self._report_coverage,
        }
        
        # Use dynamic role registration
        role = AgentRole("test_runner")
        super().__init__(role, custom_handlers)
        logger.info("✅ TestRunnerAgent initialized")
    
    async def _run_tests(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """
        Runs specified tests and returns the results.
        
        Capability: RUN_TESTS
        """
        try:
            arguments = task.get("arguments", {})
            
            import asyncio
            import json
            args = task.get('arguments', {})
            test_script = args.get('test_script')
            if not test_script:
                return {'success': False, 'error': 'Test script not provided'}
            process = await asyncio.create_subprocess_exec(
                'python', test_script,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            stdout_bytes, stderr_bytes = await process.communicate()
            output_data = {'stdout': stdout_bytes.decode('utf-8', 'replace'), 'stderr': stderr_bytes.decode('utf-8', 'replace')}
            return {'success': process.returncode == 0, 'output': output_data}
            
        except Exception as e:
            logger.error(f"_run_tests failed: {e}")
            return {"success": False, "error": str(e)}

    async def _report_coverage(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """
        Reports code coverage after running tests.
        
        Capability: REPORT_COVERAGE
        """
        try:
            arguments = task.get("arguments", {})
            
            import json
            from xml.etree import ElementTree as ET
            args = task.get('arguments', {})
            coverage_xml = args.get('coverage_xml')
            if not coverage_xml:
                return {'success': False, 'error': 'Coverage XML file not provided'}
            tree = ET.parse(coverage_xml)
            root = tree.getroot()
            packages = root.findall('.//package')
            coverage_data = []
            for package in packages:
                coverage_info = {
                    'name': package.attrib['name'],
                    'line-rate': float(package.attrib['line-rate'])
                }
                coverage_data.append(coverage_info)
            return {'success': True, 'coverage_data': coverage_data}
            
        except Exception as e:
            logger.error(f"_report_coverage failed: {e}")
            return {"success": False, "error": str(e)}



# ============================================================
# Entry Point
# ============================================================

async def main():
    """Start the TestRunnerAgent."""
    logger.info("🚀 Starting TestRunnerAgent...")
    agent = TestRunnerAgent()
    agent.start()
    
    try:
        while True:
            await asyncio.sleep(1)
    except KeyboardInterrupt:
        logger.info("🛑 TestRunnerAgent stopping...")


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    asyncio.run(main())
